# Terraform file autogenerated by Packer. It contains the latest Packer Build artifact ID.
# 2021-10-11 15:12

source_ocid = "ocid1.image.oc1.eu-frankfurt-1.aaaaaaaaodnivvmyixjjz3nz5daivb5jyu3igbw3ia3fc7eu76y2gqvziqca"
