---
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1 # Get the latest from: https://github.com/pre-commit/pre-commit-hooks/releases
  hooks:
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.52.0 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
  hooks:
    - id: terraform_validate
    - id: terraform_fmt
- repo: https://github.com/terraform-docs/terraform-docs
  rev: v0.16.0
  hooks:
    - id: terraform-docs-system
      args: ["provision"]
...